/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erikthegod.practica53;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Erikthegod
 */
public class JPanelSelects extends javax.swing.JPanel {

    private JFrame jfe;
    ArrayList dni = new ArrayList();
    ArrayList tablas = new ArrayList();
    GestorBBDD ges = new GestorBBDD();

    public JPanelSelects(JFrame _jfe) {
        try {
            initComponents();
            this.jfe = _jfe;
            dni = ges.recogerDni();
            tablas = ges.recogerTablas();
            for (int i = 0; i < dni.size(); i++) {
                jcbDnis.addItem((String) dni.get(i));
            }
            for (int i = 0; i < tablas.size(); i++) {
                jcbTablas.addItem((String) tablas.get(i));
            }
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error al conectar con BBDD");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbDisponibles = new javax.swing.JButton();
        jbPropietarios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaSelects = new javax.swing.JTextArea();
        jbBusDni = new javax.swing.JButton();
        jcbDnis = new javax.swing.JComboBox<>();
        jbInfo = new javax.swing.JButton();
        jcbTablas = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 102, 102));
        setPreferredSize(new java.awt.Dimension(658, 521));

        jbDisponibles.setText("Coches disponibles");
        jbDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDisponiblesActionPerformed(evt);
            }
        });

        jbPropietarios.setText("Mostrar Propietarios");
        jbPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPropietariosActionPerformed(evt);
            }
        });

        jtaSelects.setColumns(20);
        jtaSelects.setRows(5);
        jScrollPane1.setViewportView(jtaSelects);

        jbBusDni.setText("Buscar por dni");
        jbBusDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBusDniActionPerformed(evt);
            }
        });

        jbInfo.setText("Informacion sobre la tabla");
        jbInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbInfo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbBusDni)
                        .addGap(31, 31, 31)
                        .addComponent(jcbDnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbPropietarios)
                    .addComponent(jbDisponibles)
                    .addComponent(jcbTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbDisponibles)
                        .addGap(87, 87, 87)
                        .addComponent(jbPropietarios)
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbBusDni)
                            .addComponent(jcbDnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addComponent(jbInfo)
                        .addGap(18, 18, 18)
                        .addComponent(jcbTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDisponiblesActionPerformed
        try {
            ges.ejercicio2(jtaSelects);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error al conectar con BBDD");
        }
    }//GEN-LAST:event_jbDisponiblesActionPerformed

    private void jbPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPropietariosActionPerformed
        try {
            ges.ejercicio3(jtaSelects);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error al conectar con BBDD");
        }
    }//GEN-LAST:event_jbPropietariosActionPerformed

    private void jbBusDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBusDniActionPerformed
        try {
            ges.ejercicioPlus((String) jcbDnis.getSelectedItem(), jtaSelects);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error al conectar con BBDD");
        }
    }//GEN-LAST:event_jbBusDniActionPerformed

    private void jbInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInfoActionPerformed
        try {
            ges.ejercicio8((String) jcbTablas.getSelectedItem(), jtaSelects);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error al conectar con BBDD");
        }
    }//GEN-LAST:event_jbInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBusDni;
    private javax.swing.JButton jbDisponibles;
    private javax.swing.JButton jbInfo;
    private javax.swing.JButton jbPropietarios;
    private javax.swing.JComboBox<String> jcbDnis;
    private javax.swing.JComboBox<String> jcbTablas;
    private javax.swing.JTextArea jtaSelects;
    // End of variables declaration//GEN-END:variables
}
